---
title: Hawkless Builders
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  staff:
    title: Staff
    output: true
  testimonials:
    title: Testimonials
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
baseurl: 
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
exclude:
- README.md
